---
- name: Set up kubeadm
  hosts: all
  remote_user: kuberoot

  tasks:
    # - name: Disable swap
    #   shell: |
    #     swapoff -a
    - name: Package installation
      apt:
        name:
          - lsb-release
          - curl
          - gnupg
          - ca-certificates
        state: latest

      # - name: Install containerd
      #   become: true
      #   become_user: root
      #   package:
      #     name: containerd.io
      #     state: present
